# Generated by Django 5.0.6 on 2024-06-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(unique=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('what_the_image_is', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
