# Generated by Django 5.0.6 on 2024-06-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_generation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageinfo',
            name='image_url',
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
