# Generated by Django 5.0.6 on 2024-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_generation', '0002_remove_imageinfo_image_url_imageinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinfo',
            name='image_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
