# Generated by Django 5.0.6 on 2024-06-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_generation', '0003_imageinfo_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinfo',
            name='dimensions',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
